site_name: Benchmarks' Benchmark

theme:
    name: material
    custom_dir: overrides
    features:
        - toc.integrate

extra_css:
    - css/footer.css

plugins:
    - macros

markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - admonition

nav:
  - "About B2": index.md
  - "B2 Results":
    - "Scores (Relative)": scores-relative.md
    - "Scores (Absolute)": scores-absolute.md
  - "Submitting a Benchmark to be Benchmarked":
    - "Threat Registry": threat-registry.md
    - "Available Threat Responses": risk-response.md
    - "Questionnaire": questionnaire.md
