site_name: Benchmarks' Benchmark

theme:
    name: material
    custom_dir: overrides
    features:
        - toc.integrate
    palette:
        scheme: slate
        primary: custom
        accent: custom
    favicon: images/favicon-32x32.png
    logo: images/ulresearchinst_logo_horz_wht_rgb.png


extra_css:
    - css/footer.css
    - css/extra.css

plugins:
    - macros

markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - admonition

nav:
  - "About B2": index.md
  - "B2 Results":
    - "Scores (Relative)": scores-relative.md
    - "Scores (Absolute)": scores-absolute.md
  - "Submitting a Benchmark to be Benchmarked":
    - "Failure Mode Registry": threat-registry.md
    - "Available Mitigations": risk-response.md
    - "Questionnaire": questionnaire.md
