site_name: Benchmarks' Benchmark

theme:
    name: material
    features:
        - toc.integrate

plugins:
    - macros

markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - admonition

nav:
  - "Home": index.md
  - "Results":
    - "Absolute Risk Summary": data/absolute-risk-summary-table.md
    - "Relative Risk Summary": data/relative-risk-summary-table.md
    - "Risk Response Table": data/risk-response-table.md
    - "Threat Registry Table": data/threat-registry-table.md
  - "Questionnaire": questionnaire.md
