site_name: Benchmarks' Benchmark

theme:
    name: material
    features:
        - toc.integrate

plugins:
    - macros

markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - admonition

nav:
  - "About B2": index.md
  - "B2 Results":
    - "Scores (Relative)": data/relative-risk-summary-table.md
    - "Scores (Absolute)": data/absolute-risk-summary-table.md
  - "Submitting a Benchmark to be Benchmarked":
    - "Threat Registry": data/threat-registry-table.md
    - "Available Threat Responses": data/risk-response-table.md
    - "Questionnaire": questionnaire.md
